var namespacehermes =
[
    [ "adapter", null, [
      [ "fs", null, [
        [ "AdapterStat", "structhermes_1_1adapter_1_1fs_1_1_adapter_stat.html", "structhermes_1_1adapter_1_1fs_1_1_adapter_stat" ],
        [ "BlobPlacementIter", "structhermes_1_1adapter_1_1fs_1_1_blob_placement_iter.html", "structhermes_1_1adapter_1_1fs_1_1_blob_placement_iter" ],
        [ "File", "structhermes_1_1adapter_1_1fs_1_1_file.html", "structhermes_1_1adapter_1_1fs_1_1_file" ],
        [ "Filesystem", "classhermes_1_1adapter_1_1fs_1_1_filesystem.html", "classhermes_1_1adapter_1_1fs_1_1_filesystem" ],
        [ "HermesRequest", "structhermes_1_1adapter_1_1fs_1_1_hermes_request.html", "structhermes_1_1adapter_1_1fs_1_1_hermes_request" ],
        [ "IoOptions", "structhermes_1_1adapter_1_1fs_1_1_io_options.html", "structhermes_1_1adapter_1_1fs_1_1_io_options" ],
        [ "IoStatus", "structhermes_1_1adapter_1_1fs_1_1_io_status.html", "structhermes_1_1adapter_1_1fs_1_1_io_status" ],
        [ "MetadataManager", "classhermes_1_1adapter_1_1fs_1_1_metadata_manager.html", "classhermes_1_1adapter_1_1fs_1_1_metadata_manager" ]
      ] ],
      [ "mpiio", null, [
        [ "API", "classhermes_1_1adapter_1_1mpiio_1_1_a_p_i.html", "classhermes_1_1adapter_1_1mpiio_1_1_a_p_i" ],
        [ "MpiioFS", "classhermes_1_1adapter_1_1mpiio_1_1_mpiio_f_s.html", "classhermes_1_1adapter_1_1mpiio_1_1_mpiio_f_s" ],
        [ "MpiioSeekModeConv", "classhermes_1_1adapter_1_1mpiio_1_1_mpiio_seek_mode_conv.html", "classhermes_1_1adapter_1_1mpiio_1_1_mpiio_seek_mode_conv" ]
      ] ],
      [ "posix", null, [
        [ "API", "classhermes_1_1adapter_1_1posix_1_1_a_p_i.html", "classhermes_1_1adapter_1_1posix_1_1_a_p_i" ],
        [ "PosixFS", "classhermes_1_1adapter_1_1posix_1_1_posix_f_s.html", "classhermes_1_1adapter_1_1posix_1_1_posix_f_s" ]
      ] ],
      [ "pubsub", "namespacehermes_1_1adapter_1_1pubsub.html", "namespacehermes_1_1adapter_1_1pubsub" ],
      [ "stdio", null, [
        [ "API", "classhermes_1_1adapter_1_1stdio_1_1_a_p_i.html", "classhermes_1_1adapter_1_1stdio_1_1_a_p_i" ],
        [ "StdioFS", "classhermes_1_1adapter_1_1stdio_1_1_stdio_f_s.html", "classhermes_1_1adapter_1_1stdio_1_1_stdio_f_s" ]
      ] ],
      [ "vfd", null, [
        [ "test", null, [
          [ "Arguments", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_arguments.html", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_arguments" ],
          [ "Hdf5Api", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_hdf5_api.html", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_hdf5_api" ],
          [ "MuteHdf5Errors", "classhermes_1_1adapter_1_1vfd_1_1test_1_1_mute_hdf5_errors.html", "classhermes_1_1adapter_1_1vfd_1_1test_1_1_mute_hdf5_errors" ],
          [ "RwIds", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_rw_ids.html", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_rw_ids" ],
          [ "TestInfo", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_test_info.html", "structhermes_1_1adapter_1_1vfd_1_1test_1_1_test_info" ]
        ] ]
      ] ],
      [ "AbstractMapper", "classhermes_1_1adapter_1_1_abstract_mapper.html", "classhermes_1_1adapter_1_1_abstract_mapper" ],
      [ "BalancedMapper", "classhermes_1_1adapter_1_1_balanced_mapper.html", "classhermes_1_1adapter_1_1_balanced_mapper" ],
      [ "BlobPlacement", "structhermes_1_1adapter_1_1_blob_placement.html", "structhermes_1_1adapter_1_1_blob_placement" ],
      [ "InterceptorList", "structhermes_1_1adapter_1_1_interceptor_list.html", "structhermes_1_1adapter_1_1_interceptor_list" ],
      [ "MapperFactory", "classhermes_1_1adapter_1_1_mapper_factory.html", "classhermes_1_1adapter_1_1_mapper_factory" ],
      [ "MetadataManager", "classhermes_1_1adapter_1_1_metadata_manager.html", "classhermes_1_1adapter_1_1_metadata_manager" ]
    ] ],
    [ "api", null, [
      [ "BlobInfo", "structhermes_1_1api_1_1_blob_info.html", "structhermes_1_1api_1_1_blob_info" ],
      [ "Bucket", "classhermes_1_1api_1_1_bucket.html", "classhermes_1_1api_1_1_bucket" ],
      [ "Context", "structhermes_1_1api_1_1_context.html", "structhermes_1_1api_1_1_context" ],
      [ "Hermes", "classhermes_1_1api_1_1_hermes.html", "classhermes_1_1api_1_1_hermes" ],
      [ "MinimizeIoTimeOptions", "structhermes_1_1api_1_1_minimize_io_time_options.html", "structhermes_1_1api_1_1_minimize_io_time_options" ],
      [ "PersistTrait", "structhermes_1_1api_1_1_persist_trait.html", "structhermes_1_1api_1_1_persist_trait" ],
      [ "PlacementPolicyConv", "classhermes_1_1api_1_1_placement_policy_conv.html", "classhermes_1_1api_1_1_placement_policy_conv" ],
      [ "Trait", "structhermes_1_1api_1_1_trait.html", "structhermes_1_1api_1_1_trait" ],
      [ "VBucket", "classhermes_1_1api_1_1_v_bucket.html", "classhermes_1_1api_1_1_v_bucket" ],
      [ "WriteOnlyTrait", "structhermes_1_1api_1_1_write_only_trait.html", "structhermes_1_1api_1_1_write_only_trait" ]
    ] ],
    [ "testing", null, [
      [ "TargetViewState", "structhermes_1_1testing_1_1_target_view_state.html", "structhermes_1_1testing_1_1_target_view_state" ]
    ] ],
    [ "Arena", "structhermes_1_1_arena.html", "structhermes_1_1_arena" ],
    [ "ArenaInfo", "structhermes_1_1_arena_info.html", "structhermes_1_1_arena_info" ],
    [ "Array2DIdx", "structhermes_1_1_array2_d_idx.html", "structhermes_1_1_array2_d_idx" ],
    [ "Blob", "structhermes_1_1_blob.html", "structhermes_1_1_blob" ],
    [ "BlobID", "unionhermes_1_1_blob_i_d.html", "unionhermes_1_1_blob_i_d" ],
    [ "BlobInfo", "structhermes_1_1_blob_info.html", "structhermes_1_1_blob_info" ],
    [ "BlobInfoMap", "structhermes_1_1_blob_info_map.html", "structhermes_1_1_blob_info_map" ],
    [ "BoArgs", "unionhermes_1_1_bo_args.html", "unionhermes_1_1_bo_args" ],
    [ "BoTask", "structhermes_1_1_bo_task.html", "structhermes_1_1_bo_task" ],
    [ "BucketID", "unionhermes_1_1_bucket_i_d.html", "unionhermes_1_1_bucket_i_d" ],
    [ "BucketInfo", "structhermes_1_1_bucket_info.html", "structhermes_1_1_bucket_info" ],
    [ "BufferHeader", "structhermes_1_1_buffer_header.html", "structhermes_1_1_buffer_header" ],
    [ "BufferID", "unionhermes_1_1_buffer_i_d.html", "unionhermes_1_1_buffer_i_d" ],
    [ "BufferIdArray", "structhermes_1_1_buffer_id_array.html", "structhermes_1_1_buffer_id_array" ],
    [ "BufferIdHash", "structhermes_1_1_buffer_id_hash.html", "structhermes_1_1_buffer_id_hash" ],
    [ "BufferInfo", "structhermes_1_1_buffer_info.html", "structhermes_1_1_buffer_info" ],
    [ "BufferOrganizer", "structhermes_1_1_buffer_organizer.html", "structhermes_1_1_buffer_organizer" ],
    [ "BufferPool", "structhermes_1_1_buffer_pool.html", "structhermes_1_1_buffer_pool" ],
    [ "ChunkedIdList", "structhermes_1_1_chunked_id_list.html", "structhermes_1_1_chunked_id_list" ],
    [ "ClientRpcContext", "structhermes_1_1_client_rpc_context.html", "structhermes_1_1_client_rpc_context" ],
    [ "ClientThalliumState", "structhermes_1_1_client_thallium_state.html", "structhermes_1_1_client_thallium_state" ],
    [ "CommunicationContext", "structhermes_1_1_communication_context.html", "structhermes_1_1_communication_context" ],
    [ "Config", "structhermes_1_1_config.html", "structhermes_1_1_config" ],
    [ "DebugHeapAllocation", "structhermes_1_1_debug_heap_allocation.html", "structhermes_1_1_debug_heap_allocation" ],
    [ "DebugState", "structhermes_1_1_debug_state.html", "structhermes_1_1_debug_state" ],
    [ "Device", "structhermes_1_1_device.html", "structhermes_1_1_device" ],
    [ "DPE", "classhermes_1_1_d_p_e.html", "classhermes_1_1_d_p_e" ],
    [ "DPEFactory", "classhermes_1_1_d_p_e_factory.html", "classhermes_1_1_d_p_e_factory" ],
    [ "FreeBlock", "structhermes_1_1_free_block.html", "structhermes_1_1_free_block" ],
    [ "FreeBlockHeader", "structhermes_1_1_free_block_header.html", "structhermes_1_1_free_block_header" ],
    [ "GlobalSystemViewState", "structhermes_1_1_global_system_view_state.html", "structhermes_1_1_global_system_view_state" ],
    [ "Heap", "structhermes_1_1_heap.html", "structhermes_1_1_heap" ],
    [ "IdList", "structhermes_1_1_id_list.html", "structhermes_1_1_id_list" ],
    [ "IdMap", "structhermes_1_1_id_map.html", "structhermes_1_1_id_map" ],
    [ "LinearProgram", "classhermes_1_1_linear_program.html", "classhermes_1_1_linear_program" ],
    [ "MetadataManager", "structhermes_1_1_metadata_manager.html", "structhermes_1_1_metadata_manager" ],
    [ "MinimizeIoTime", "classhermes_1_1_minimize_io_time.html", "classhermes_1_1_minimize_io_time" ],
    [ "MPIState", "structhermes_1_1_m_p_i_state.html", "structhermes_1_1_m_p_i_state" ],
    [ "Random", "classhermes_1_1_random.html", "classhermes_1_1_random" ],
    [ "RoundRobin", "classhermes_1_1_round_robin.html", "classhermes_1_1_round_robin" ],
    [ "RpcContext", "structhermes_1_1_rpc_context.html", "structhermes_1_1_rpc_context" ],
    [ "RwLock", "structhermes_1_1_rw_lock.html", "structhermes_1_1_rw_lock" ],
    [ "ScopedTemporaryMemory", "structhermes_1_1_scoped_temporary_memory.html", "structhermes_1_1_scoped_temporary_memory" ],
    [ "SharedMemoryContext", "structhermes_1_1_shared_memory_context.html", "structhermes_1_1_shared_memory_context" ],
    [ "ShmemClientInfo", "structhermes_1_1_shmem_client_info.html", "structhermes_1_1_shmem_client_info" ],
    [ "ShmemString", "structhermes_1_1_shmem_string.html", "structhermes_1_1_shmem_string" ],
    [ "Singleton", "classhermes_1_1_singleton.html", "classhermes_1_1_singleton" ],
    [ "Stats", "structhermes_1_1_stats.html", "structhermes_1_1_stats" ],
    [ "SwapBlob", "structhermes_1_1_swap_blob.html", "structhermes_1_1_swap_blob" ],
    [ "SystemViewState", "structhermes_1_1_system_view_state.html", "structhermes_1_1_system_view_state" ],
    [ "Target", "structhermes_1_1_target.html", "structhermes_1_1_target" ],
    [ "TargetID", "unionhermes_1_1_target_i_d.html", "unionhermes_1_1_target_i_d" ],
    [ "TargetInfo", "structhermes_1_1_target_info.html", "structhermes_1_1_target_info" ],
    [ "TemporaryMemory", "structhermes_1_1_temporary_memory.html", "structhermes_1_1_temporary_memory" ],
    [ "ThalliumState", "structhermes_1_1_thallium_state.html", "structhermes_1_1_thallium_state" ],
    [ "ThreadPool", "classhermes_1_1_thread_pool.html", "classhermes_1_1_thread_pool" ],
    [ "Thresholds", "structhermes_1_1_thresholds.html", "structhermes_1_1_thresholds" ],
    [ "Ticket", "structhermes_1_1_ticket.html", "structhermes_1_1_ticket" ],
    [ "TicketMutex", "structhermes_1_1_ticket_mutex.html", "structhermes_1_1_ticket_mutex" ],
    [ "VBucketID", "unionhermes_1_1_v_bucket_i_d.html", "unionhermes_1_1_v_bucket_i_d" ],
    [ "VBucketInfo", "structhermes_1_1_v_bucket_info.html", "structhermes_1_1_v_bucket_info" ],
    [ "ViolationInfo", "structhermes_1_1_violation_info.html", "structhermes_1_1_violation_info" ]
];